# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.create(name: "Jeans 1", details: "Trendy and stylish for the new generation", price: "30", stock: "100")
Product.create(name: "Jeans 2", details: "Trendy and stylish for the new generation", price: "30", stock: "100")
Product.create(name: "Jeans 3", details: "Trendy and stylish for the new generation", price: "30", stock: "100")
Product.create(name: "Jeans 4", details: "Trendy and stylish for the new generation", price: "30", stock: "100")
Product.create(name: "Jeans 5", details: "Trendy and stylish for the new generation", price: "30", stock: "100")
Product.create(name: "Crop Top 1", details: "Trendy and stylish for the new generation", price: "20", stock: "102")
Product.create(name: "Crop Top 2", details: "Trendy and stylish for the new generation", price: "20", stock: "102")
Product.create(name: "Crop Top 3", details: "Trendy and stylish for the new generation", price: "20", stock: "102")
Product.create(name: "Crop Top 4", details: "Trendy and stylish for the new generation", price: "20", stock: "102")
Product.create(name: "Crop Top 5", details: "Trendy and stylish for the new generation", price: "20", stock: "102")
Product.create(name: "Saree 1", details: "Trendy and stylish for the new generation", price: "50", stock: "150")
Product.create(name: "Saree 2", details: "Trendy and stylish for the new generation", price: "50", stock: "150")
Product.create(name: "Saree 3", details: "Trendy and stylish for the new generation", price: "50", stock: "150")
Product.create(name: "Saree 4", details: "Trendy and stylish for the new generation", price: "50", stock: "150")
Product.create(name: "Saree 5", details: "Trendy and stylish for the new generation", price: "50", stock: "150")
Product.create(name: "Plazoo 1", details: "Trendy and stylish for the new generation", price: "40", stock: "600")
Product.create(name: "Plazoo 2", details: "Trendy and stylish for the new generation", price: "40", stock: "600")
Product.create(name: "Plazoo 3", details: "Trendy and stylish for the new generation", price: "40", stock: "600")
Product.create(name: "Plazoo 4", details: "Trendy and stylish for the new generation", price: "40", stock: "600")
Product.create(name: "Plazoo 5", details: "Trendy and stylish for the new generation", price: "40", stock: "600")
Product.create(name: "Shoes 1", details: "Trendy and stylish for the new generation", price: "35.5", stock: "800")
Product.create(name: "Shoes 2", details: "Trendy and stylish for the new generation", price: "35.5", stock: "800")
Product.create(name: "Shoes 3", details: "Trendy and stylish for the new generation", price: "35.5", stock: "800")
Product.create(name: "Shoes 4", details: "Trendy and stylish for the new generation", price: "35.5", stock: "800")
Product.create(name: "Shoes 5", details: "Trendy and stylish for the new generation", price: "35.5", stock: "800")
Product.create(name: "Shirts 1", details: "Trendy and stylish for the new generation", price: "31", stock: "130")
Product.create(name: "Shirts 2", details: "Trendy and stylish for the new generation", price: "31", stock: "130")
Product.create(name: "Shirts 3", details: "Trendy and stylish for the new generation", price: "31", stock: "130")
Product.create(name: "Shirts 4", details: "Trendy and stylish for the new generation", price: "31", stock: "130")
Product.create(name: "Shirts 5", details: "Trendy and stylish for the new generation", price: "31", stock: "130")
Product.create(name: "Casual Shirts 1", details: "Trendy and stylish for the new generation", price: "30.99", stock: "10")
Product.create(name: "Casual Shirts 2", details: "Trendy and stylish for the new generation", price: "30.99", stock: "10")
Product.create(name: "Casual Shirts 3", details: "Trendy and stylish for the new generation", price: "30.99", stock: "10")
Product.create(name: "Casual Shirts 4", details: "Trendy and stylish for the new generation", price: "30.99", stock: "10")
Product.create(name: "Casual Shirts 5", details: "Trendy and stylish for the new generation", price: "30.99", stock: "10")
